### PR TITLE
remove sudo from tests

### PR DESCRIPTION
**Pull request by jessfraz**
use a version of runc with patches

cc @AkihiroSuda

### CODE REVIEW

**Comment by jessfraz** [comment]
oh doi hahaha I usually do that, I am like a static binary queen

**Comment by jessfraz** [comment]
I re-uploaded as a static binary for the future :)

**Comment by AkihiroSuda** [comment]
Travis result disappeared?

**Comment by jessfraz** [comment]
yeah I was trying to re-trigger but now it's not coming backkkk wahhhh computers..

**Comment by jessfraz** [comment]
https://www.traviscistatus.com/incidents/f4j8x61l4qgc

**Pull request merged**
